spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# spring.datasource.initialization-mode=embedded
spring.sql.init.mode=embedded
applicationinsights.connection.string=InstrumentationKey=27c32fef-e9c9-4988-91b1-b62eb3a15ad2;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=12f2cf2b-273a-42f7-94af-4cc851a995c0
