apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: prod
spec:
  replicas: 2   # HPA will scale from here
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: DB_URL
              value: "${DB_URL}"

            - name: DB_USERNAME
              value: "${DB_USERNAME}"

            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"

            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: "${APPLICATIONINSIGHTS_CONNECTION_STRING}"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
