apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "stage"
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: "InstrumentationKey=27c32fef-e9c9-4988-91b1-b62eb3a15ad2;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=12f2cf2b-273a-42f7-94af-4cc851a995c0"

